"""Initial schema

Revision ID: 435e5a4670a9
Revises: c543be6dd922
Create Date: 2025-11-24 12:04:11.546189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '435e5a4670a9'
down_revision: Union[str, None] = 'c543be6dd922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'resource_type', name='uq_metadata_resource'),
    schema='pycharter'
    )
    op.create_table('ownership',
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('resource_id'),
    schema='pycharter'
    )
    op.create_table('schemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('schema_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_schemas_name_version'),
    schema='pycharter'
    )
    op.create_table('coercion_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['pycharter.schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', 'version', name='uq_coercion_rules_schema_version'),
    schema='pycharter'
    )
    op.create_table('governance_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_definition', sa.JSON(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['pycharter.schemas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pycharter'
    )
    op.create_table('validation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['pycharter.schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', 'version', name='uq_validation_rules_schema_version'),
    schema='pycharter'
    )
    op.drop_table('minimum_groundtime')
    op.drop_table('mel_to_constraint')
    op.drop_table('iata_fleet_type')
    op.drop_table('compartment')
    op.drop_index(op.f('idx_metadata_resource'), table_name='metadata')
    op.drop_table('metadata')
    op.drop_table('leg_50_rows')
    op.drop_index(op.f('idx_validation_schema_id'), table_name='validation_rules')
    op.drop_index(op.f('idx_validation_version'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_table('dst_info')
    op.drop_index(op.f('idx_schemas_name'), table_name='schemas')
    op.drop_index(op.f('idx_schemas_version'), table_name='schemas')
    op.drop_table('schemas')
    op.drop_table('check_basics')
    op.drop_table('leg_remark_50rows')
    op.drop_table('leg_check_50rows')
    op.drop_table('ownership')
    op.drop_table('leg_misc_hist_50rows')
    op.drop_table('change_reason')
    op.drop_table('delay_code')
    op.drop_table('season')
    op.drop_table('subfleet')
    op.drop_table('sector_constraints')
    op.drop_table('aircraft')
    op.drop_table('leg_misc_50rows')
    op.drop_table('constraint_code_desc')
    op.drop_index(op.f('idx_coercion_schema_id'), table_name='coercion_rules')
    op.drop_index(op.f('idx_coercion_version'), table_name='coercion_rules')
    op.drop_table('coercion_rules')
    op.drop_table('leg_history_50rows')
    op.drop_table('pycharter_schema_version')
    op.drop_table('ac_restriction')
    op.drop_table('ap_basics')
    op.drop_table('leg_delay_50rows')
    op.drop_index(op.f('idx_governance_schema_id'), table_name='governance_rules')
    op.drop_table('governance_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rule_definition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('schema_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], name=op.f('governance_rules_schema_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('governance_rules_pkey'))
    )
    op.create_index(op.f('idx_governance_schema_id'), 'governance_rules', ['schema_id'], unique=False)
    op.create_table('leg_delay_50rows',
    sa.Column('leg_delay_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('leg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('delay_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('delay_minutes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('delay_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delay_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delay_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('ap_basics',
    sa.Column('iata_ap_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('valid_since', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valid_until', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icao_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ap_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('dst_zone_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('area', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('time_zone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('coord_longitude', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('coord_latitude', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('external_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ap_name_nls', sa.VARCHAR(length=200), autoincrement=False, nullable=True)
    )
    op.create_table('ac_restriction',
    sa.Column('r_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('update_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('registration', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('restr_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('mark', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('technical_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workorder_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valid_since', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valid_until', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expire_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expire_total_fh_hours', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('expire_total_fh_minutes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('expire_total_cycles', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('entry_dt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entry_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ata_chapter', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ata_subchapter', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ata_section', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ata_item', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ata_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('limitations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('operating_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('telex', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_object_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ack_state', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ack_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ack_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('pycharter_schema_version',
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name=op.f('pycharter_schema_version_pkey'))
    )
    op.create_table('leg_history_50rows',
    sa.Column('leg_history_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('leg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('history_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('history_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('history_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('history_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('coercion_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schema_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], name=op.f('coercion_rules_schema_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('coercion_rules_pkey')),
    sa.UniqueConstraint('schema_id', 'version', name=op.f('coercion_rules_schema_id_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_coercion_version'), 'coercion_rules', ['version'], unique=False)
    op.create_index(op.f('idx_coercion_schema_id'), 'coercion_rules', ['schema_id'], unique=False)
    op.create_table('constraint_code_desc',
    sa.Column('id_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tx_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctx_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delete_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('basetx_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('res_model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('constraint_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('editable', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aircraft_label_letter', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('valid_for_ops', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('valid_for_sched', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valid_for_ac_owner', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('valid_for_ac_subtypes', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('currind_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telex_relevant', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('ground_handling_relevant', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('leg_misc_50rows',
    sa.Column('leg_misc_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('leg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('misc_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('misc_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('misc_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('misc_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('misc_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('aircraft',
    sa.Column('registration', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valid_since', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valid_until', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ac_operator', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ac_owner', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ac_subtype', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ac_logical_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ac_state', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('dry_operating_wgt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('max_takeoff_wgt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cargo_capacity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fuel_capacity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('avg_fuel_consum', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ac_index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('crewsize_cockpit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('crewsize_cabin', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('std_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ap_restriction', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ac_owner_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ac_subtype_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ac_category', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fuel_measure_unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ac_callsign', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('radio', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('noise', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('special_equipment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acars', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('alt_reg', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('std_version_alt_1', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('std_version_alt_2', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('std_version_alt_3', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('std_version_alt_4', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ils_equipment', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('autoland', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('homebase', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    op.create_table('sector_constraints',
    sa.Column('res_model_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('constraint_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('match_orig_code_indicator', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('match_orig_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('match_dest_code_indicator', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('match_dest_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('match_blocktime_from', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('match_blocktime_to', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('match_flight_carrier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('match_flight_number_from', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('match_flight_number_to', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('match_aircraft_owner', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('match_type_indicator', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('match_aircraft_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('match_configuration_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('flight_carrier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('flight_number_from', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('flight_number_to', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('aircraft_owner', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('type_indicator', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('aircraft_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('configuration_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dep_time_range_from_lt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dep_time_range_to_lt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('arr_time_range_from_lt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('arr_time_range_to_lt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discontinue_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('days_of_operation', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('season_indicator', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('required_or_forbidden', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('blocktime_from', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('blocktime_to', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('match_dep_time_range_from_lt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('match_dep_time_range_to_lt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('match_arr_time_range_from_lt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('match_arr_time_range_to_lt', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('subfleet',
    sa.Column('res_model_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('aircraft_owner', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('subfleet_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discontinue_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aircraft_subtype', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fleet_print_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('rotational_flag', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('standard_configuration', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payload', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('mtom', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('max_range', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('noise_category', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('average_speed', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('season',
    sa.Column('season', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('peekweek_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coord_state', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('delay_code',
    sa.Column('delay_code_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('delay_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('delay_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delay_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('delay_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('delay_active', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('change_reason',
    sa.Column('change_reason_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('change_reason_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('change_reason_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('change_reason_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('change_reason_active', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('leg_misc_hist_50rows',
    sa.Column('leg_misc_hist_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('leg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('misc_hist_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('misc_hist_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('misc_hist_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('misc_hist_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('misc_hist_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('ownership',
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('ownership_pkey'))
    )
    op.create_table('leg_check_50rows',
    sa.Column('leg_check_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('leg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('check_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('check_result', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('check_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('check_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('check_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('leg_remark_50rows',
    sa.Column('leg_remark_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('leg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('remark_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('remark_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remark_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remark_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('check_basics',
    sa.Column('check_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('check_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('check_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('check_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('check_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('check_active', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('schemas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('schemas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('schema_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='schemas_pkey'),
    sa.UniqueConstraint('name', 'version', name='schemas_name_version_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_schemas_version'), 'schemas', ['version'], unique=False)
    op.create_index(op.f('idx_schemas_name'), 'schemas', ['name'], unique=False)
    op.create_table('dst_info',
    sa.Column('dst_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dst_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('dst_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dst_country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dst_start_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dst_end_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dst_offset_hours', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('validation_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schema_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], name=op.f('validation_rules_schema_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('validation_rules_pkey')),
    sa.UniqueConstraint('schema_id', 'version', name=op.f('validation_rules_schema_id_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_validation_version'), 'validation_rules', ['version'], unique=False)
    op.create_index(op.f('idx_validation_schema_id'), 'validation_rules', ['schema_id'], unique=False)
    op.create_table('leg_50_rows',
    sa.Column('leg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('leg_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('leg_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leg_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leg_airline', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('leg_aircraft', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('leg_flight_no', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('leg_airport_origin', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('leg_airport_destination', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('leg_status', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('metadata_pkey')),
    sa.UniqueConstraint('resource_id', 'resource_type', name=op.f('metadata_resource_id_resource_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_metadata_resource'), 'metadata', ['resource_id', 'resource_type'], unique=False)
    op.create_table('compartment',
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('priority', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('booking_classes', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('three_comp_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('iata_fleet_type',
    sa.Column('res_model_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('aircraft_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('aircraft_group', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('icao_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('body_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('mel_to_constraint',
    sa.Column('ata_chapter', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ata_subchapter', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ata_section', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ata_item', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('constraint_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ac_owner', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ac_subtype', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    op.create_table('minimum_groundtime',
    sa.Column('groundtime_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('groundtime_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('groundtime_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('groundtime_minutes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('groundtime_airport', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('groundtime_aircraft', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('groundtime_active', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_update_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_table('validation_rules', schema='pycharter')
    op.drop_table('governance_rules', schema='pycharter')
    op.drop_table('coercion_rules', schema='pycharter')
    op.drop_table('schemas', schema='pycharter')
    op.drop_table('ownership', schema='pycharter')
    op.drop_table('metadata', schema='pycharter')
    # ### end Alembic commands ###
