"""Add new entity models and rename metadata table

Revision ID: a8acb1d9a1d2
Revises: 435e5a4670a9
Create Date: 2025-11-25 12:44:52.662631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8acb1d9a1d2'
down_revision: Union[str, None] = '435e5a4670a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='pycharter'
    )
    op.create_table('data_feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feed_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='pycharter'
    )
    op.create_table('domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_domain_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='pycharter'
    )
    # Rename metadata table to metadata_record
    op.rename_table('metadata', 'metadata_record', schema='pycharter')
    # Update the unique constraint name
    op.drop_constraint('uq_metadata_resource', 'metadata_record', schema='pycharter', type_='unique')
    op.create_unique_constraint('uq_metadata_record_resource', 'metadata_record', ['resource_id', 'resource_type'], schema='pycharter')
    # Ownership, schemas, coercion_rules, validation_rules, governance_rules already exist
    # No need to recreate them
    op.create_table('systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_type', sa.String(length=50), nullable=True),
    sa.Column('connection_info', sa.Text(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='pycharter'
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='pycharter'
    )
    # Coercion_rules, validation_rules, governance_rules already exist
    # No need to recreate them
    op.create_table('data_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('coercion_rules_id', sa.Integer(), nullable=True),
    sa.Column('validation_rules_id', sa.Integer(), nullable=True),
    sa.Column('governance_rules_id', sa.Integer(), nullable=True),
    sa.Column('metadata_id', sa.Integer(), nullable=True),
    sa.Column('ownership_id', sa.String(length=255), nullable=True),
    sa.Column('data_feed_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_data_feed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['coercion_rules_id'], ['pycharter.coercion_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['data_feed_id'], ['pycharter.data_feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['pycharter.domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['governance_rules_id'], ['pycharter.governance_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metadata_id'], ['pycharter.metadata_record.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ownership_id'], ['pycharter.ownership.resource_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schema_id'], ['pycharter.schemas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_rules_id'], ['pycharter.validation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_data_contracts_name_version'),
    schema='pycharter'
    )
    op.create_table('data_contract_business_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_contract_id', sa.Integer(), nullable=False),
    sa.Column('business_owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_owner_id'], ['pycharter.business_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_contract_id'], ['pycharter.data_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_contract_id', 'business_owner_id', name='uq_dc_business_owner'),
    schema='pycharter'
    )
    op.create_table('data_contract_system_pulls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_contract_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_contract_id'], ['pycharter.data_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['pycharter.systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_contract_id', 'system_id', name='uq_dc_system_pull'),
    schema='pycharter'
    )
    op.create_table('data_contract_system_pushes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_contract_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_contract_id'], ['pycharter.data_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['pycharter.systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_contract_id', 'system_id', name='uq_dc_system_push'),
    schema='pycharter'
    )
    op.create_table('data_contract_system_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_contract_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_contract_id'], ['pycharter.data_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['pycharter.systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_contract_id', 'system_id', name='uq_dc_system_source'),
    schema='pycharter'
    )
    op.create_table('data_contract_team_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_contract_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_contract_id'], ['pycharter.data_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['pycharter.teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_contract_id', 'team_id', 'permission', name='uq_dc_team_access'),
    schema='pycharter'
    )
    op.create_table('data_feed_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_contract_id', sa.Integer(), nullable=False),
    sa.Column('dependency_feed_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_contract_id'], ['pycharter.data_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dependency_feed_id'], ['pycharter.data_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_contract_id', 'dependency_feed_id', name='uq_data_feed_dependency'),
    schema='pycharter'
    )
    # Don't drop existing tables - they're being kept, just metadata was renamed
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership',
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('additional_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('ownership_pkey'))
    )
    op.create_table('governance_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rule_definition', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('schema_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], name=op.f('governance_rules_schema_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('governance_rules_pkey'))
    )
    op.create_table('schemas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('schemas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('schema_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='schemas_pkey'),
    sa.UniqueConstraint('name', 'version', name='uq_schemas_name_version'),
    postgresql_ignore_search_path=False
    )
    op.create_table('metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('metadata_pkey')),
    sa.UniqueConstraint('resource_id', 'resource_type', name=op.f('uq_metadata_resource'))
    )
    op.create_table('coercion_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schema_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], name=op.f('coercion_rules_schema_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('coercion_rules_pkey')),
    sa.UniqueConstraint('schema_id', 'version', name=op.f('uq_coercion_rules_schema_version'))
    )
    op.create_table('validation_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schema_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], name=op.f('validation_rules_schema_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('validation_rules_pkey')),
    sa.UniqueConstraint('schema_id', 'version', name=op.f('uq_validation_rules_schema_version'))
    )
    op.drop_table('data_feed_dependencies', schema='pycharter')
    op.drop_table('data_contract_team_access', schema='pycharter')
    op.drop_table('data_contract_system_sources', schema='pycharter')
    op.drop_table('data_contract_system_pushes', schema='pycharter')
    op.drop_table('data_contract_system_pulls', schema='pycharter')
    op.drop_table('data_contract_business_owners', schema='pycharter')
    op.drop_table('data_contracts', schema='pycharter')
    op.drop_table('validation_rules', schema='pycharter')
    op.drop_table('governance_rules', schema='pycharter')
    op.drop_table('coercion_rules', schema='pycharter')
    op.drop_table('teams', schema='pycharter')
    op.drop_table('systems', schema='pycharter')
    op.drop_table('schemas', schema='pycharter')
    op.drop_table('ownership', schema='pycharter')
    op.drop_table('metadata_record', schema='pycharter')
    op.drop_table('domains', schema='pycharter')
    op.drop_table('data_feeds', schema='pycharter')
    op.drop_table('business_owners', schema='pycharter')
    # ### end Alembic commands ###
